pub mod audit;
pub mod auth;
pub mod catalog;
pub mod shadow;
pub mod cli;
pub mod config;
pub mod config_pipeline;
pub mod domain;
pub mod engine;
pub mod error;
pub mod executor;
pub mod fs;
pub mod hardware;
pub mod ipc;
pub mod pipeline;
pub mod planner;
pub mod platform;
pub mod policy;
pub mod recovery;
pub mod resource;
pub mod safety;
pub mod scanner;
pub mod scheduler;
pub mod store;
pub mod system;
pub mod util;
pub mod verifier;
pub mod worker;

pub use config::DaemonConfig;
pub use engine::{CancellationToken, CleanEngine};
pub use error::{CleanerError, Result};
pub use ipc::client::IpcClient;
pub use ipc::protocol::{CleanParams, CleanReport, Command, DaemonStatus, Response, ResponseData};
pub use ipc::server::IpcServer;
pub use pipeline::AuthoritativeCleanPipeline;
pub use platform::{check_encryption_state, enumerate_users, get_selinux_mode, AndroidSystemInfo};
pub use scheduler::SchedulerService;
pub use store::SqliteStore;
pub use system::{DaemonContext, DaemonRunner, DaemonState};
pub use util::{format_bytes, init_logger};
pub use worker::WorkerPool;
